version: '3.7'
services:
    sam-local:
        build: ./sam-local
        container_name: sam-local
        privileged: true
        ports:
          - "3000:3000"
        env_file:
            .env
        volumes:
          - ./sam-local:/app
