version: '3.7'
services:
    # --------------------------------------------------------------------------
    # FRONTEND WRITTEN IN ANGULAR
    # --------------------------------------------------------------------------
    serverless-angular-client-ui:
        build: ./client-ui
        container_name: serverless-angular-client-ui
        env_file:
            .env
        volumes:
          - ./client-ui:/usr/src/app
          - /usr/src/app/node_modules
        ports:
          - "4200:4200"
