# ------------------------------------------------------------------------------
# CODE DOCKER COMPOSE
#
# This Docker Compose is meant to deploy/update frontend code and backend code
# to a remote environment. With this we create the Code Cloud Formation stack.
#
# Prerequisites:
# - Infrastructure Stack
# - Lambda Layer with pyjwt==1.7.1 & cryptography==2.8
#
# ------------------------------------------------------------------------------
# # Temporarily set to version 3.2 to support circle CI
# version: '3.7'
version: '3.2'
services:
    # --------------------------------------------------------------------------
    # FRONTEND WRITTEN IN ANGULAR
    # --------------------------------------------------------------------------
    serverless-angular-client-ui:
        build: ./client-ui
        container_name: serverless-deploy-angular-client-ui
        volumes:
          - ./client-ui:/usr/src/app
          - /usr/src/app/node_modules
        env_file:
          - remote.env
        command: tail -f /dev/null
    # --------------------------------------------------------------------------
    # BACKEND WRITTEN IN AWS SAM LOCAL
    # --------------------------------------------------------------------------
    serverless-lambda-api:
        build: ./api
        container_name: serverless-deploy-lambda-api
        volumes:
          - ./api:/app
        env_file:
          - remote.env
        command: tail -f /dev/null

# # Temporarily commented since not supported by circle CI
# networks:
#   default:
#     name: cheet-sheet-deploy-code
