# ------------------------------------------------------------------------------
# CODE DOCKER COMPOSE
#
# This Docker Compose is meant to deploy frontend code and backend code
# to a remote environment.
#
# What this deploys:
# - Angular code to an S3 bucket
# - Lambda Function that connects to an API Gateway
#
# Prerequisites:
# - Cognito Userpool
# - API Gateway
# - S3 Bucket for UI hosting
# - S3 Bucket for App Data Storage
# - IAM Role for a Lambda Function
#     Should have permission to update the App Data Storage bucket
#
# ------------------------------------------------------------------------------
version: '3.7'
services:
    # --------------------------------------------------------------------------
    # FRONTEND WRITTEN IN ANGULAR
    # --------------------------------------------------------------------------
    utils:
        build: ./.utils
        container_name: cheet-sheet-utils
        volumes:
          - ./utils:/usr/src/app
          - /usr/src/app/node_modules

networks:
  default:
    name: cheet-sheet-utils
