# ------------------------------------------------------------------------------
# INFRASTRUCTURE DOCKER COMPOSE
#
# This Docker Compose can deploy the Infrastructure Stack and the Networking Stack
#
# Infrastructure Stack Prerequisites:
# - None, this is the first stack deployed
#
# Networking Stack Prerequisites:
# - Infrastructure Stack
# - ACM Certifcate
# - Route53 Domain
#
# ------------------------------------------------------------------------------
version: '3.7'
services:
    # --------------------------------------------------------------------------
    # AWS-INFRASTRUCTURE DEPLOYMENT AND MAINTAINENCE WRITTEN IN aws-cdk
    # --------------------------------------------------------------------------
    serverless-aws-cdk:
        build: ./.aws-infrastructure
        container_name: serverless-aws-cdk
        env_file:
            infrastructure.env
        command: tail -F anything
        volumes:
            - ./.aws-infrastructure/package.json:/usr/src/.aws-infrastructure/package.json
            - ./.aws-infrastructure:/usr/src/app/
            - /usr/src/app/node_modules

networks:
  default:
    name: cheet-sheet-deploy-infrastructure
