AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  This is the SAM template code
  for running the CH33T SH33T app locally
  as well as to deploy it to a remote Environment

Parameters:
  LayerArn:
    Type: String
    Default: Override This Variable from the CLI


# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.7
    Timeout: 3
    MemorySize: 512
    Environment:
      Variables:
        CLIENT_UI_SUBDOMAIN: $CLIENT_UI_SUBDOMAIN
        SHEET_DATA_S3_BUCKET: $SHEET_DATA_S3_BUCKET
        COGNITO_CLIENT_ID: $COGNITO_CLIENT_ID
        COGNITO_JWKS_BASE64: $COGNITO_JWKS_BASE64
        APP_ADMIN_USER: $APP_ADMIN_USER
        PUBLIC_SHEETS_FOLDER: $PUBLIC_SHEETS_FOLDER
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:

  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: app.main
      Layers:
        - !Sub '${LayerArn}'
      Role: arn:aws:iam::056825751459:role/service-role/scratch-cheet-sheet-lambda-role
      Events:
        #/sheet
        GetSheet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet
            Method: get
        PostSheet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet
            Method: post
        #/sheet/{sheetName}
        GetSheetSheetName:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet/{sheetName}
            Method: get
        DeleteSheetSheetName:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet/{sheetName}
            Method: delete
        PutSheetSheetName:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet/{sheetName}
            Method: put
