AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: python3.7
    Timeout: 3
    MemorySize: 512
    Environment:
      Variables:
        CLIENT_UI_SUBDOMAIN: $CLIENT_UI_SUBDOMAIN
        SHEET_DATA_S3_BUCKET: $SHEET_DATA_S3_BUCKET
        COGNITO_CLIENT_ID: $COGNITO_CLIENT_ID
        COGNITO_CLIENT_SECRET: $COGNITO_CLIENT_SECRET
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:

  ApiFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: app.main
      Events:
        #/sheet
        Get_sheet:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet
            Method: get
        Post_sheet/{sheetName}:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet
            Method: post
        #/sheet/{sheetName}
        Get_sheet/{sheetName}:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet/{sheetName}
            Method: get
        Delete_sheet/{sheetName}:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet/{sheetName}
            Method: delete
        Put_sheet/{sheetName}:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /sheet/{sheetName}
            Method: put
